/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107055-g73302aa193-20220606"
#endif /* AVUTIL_FFVERSION_H */
